[package]
name = "day-01"
version = "0.1.0"
authors = ["Jean Louren√ßo <jeancarlos.bnu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
